version: '1.0'

services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
      MYSQL_USER: public
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  
    volumes:
      - db-data:/data
      - ./database/initialDB.sql:/docker-entrypoint-initdb.d/initialDB.sql
    networks: 
      - CasualShopNet

  nodejs:
    container_name: nodejs
    depends_on:
      - mysql
    build: .
    ports: 
     - "3000:3000"
    restart: unless-stopped
    networks: 
      - CasualShopNet

networks:
  CasualShopNet:
volumes:
  db-data: